Update failure.yml

diff --git a/.github/workflows/failure.yml b/.github/workflows/failure.yml
--- a/.github/workflows/failure.yml
+++ b/.github/workflows/failure.yml
@@ -6,7 +6,16 @@ on:
       - .github/workflows/failure.yml
 
 jobs:
-  fail:
+  just-fail:
+    if: github.event.pull_request.draft == true
+    runs-on: ubuntu-latest
+    steps:
+      - id: fail_step
+        run: exit 1
+
+      - run: echo ${{ steps.fail_step.outcome }} # not called
+
+  fail-with-post-process:
     if: github.event.pull_request.draft == true
     runs-on: ubuntu-latest
     steps:
@@ -14,10 +23,23 @@ jobs:
         continue-on-error: true
         run: exit 1
 
-      - run: echo ${{ steps.fail_step.outcome }} # failure
+      - name: post process regardless of sucess or failure
+        run: echo ${{ steps.fail_step.outcome }} # failure
 
-      - if: steps.fail_step.outcome == 'failure'
+      - name: make it fail when the first step failed
+        if: steps.fail_step.outcome == 'failure'
         run: exit 1
+  
+  fail-with-post-process-for-failure:
+    if: github.event.pull_request.draft == true
+    runs-on: ubuntu-latest
+    steps:
+      - id: fail_step
+        run: exit 1
+
+      - if: failure()
+        name: post process only called when the first step fails
+        run: echo ${{ steps.fail_step.outcome }} # failure
 
   succeed:
     runs-on: ubuntu-latest
